/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5e5e5e",
        "outline": "#7e7576",
        "on-tertiary-container": "#848484",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed": "#1b1b1b",
        "outline-variant": "#cfc4c5",
        "surface": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "error": "#ba1a1a",
        "on-primary-container": "#848484",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#474747",
        "primary-fixed-dim": "#c6c6c6",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-background": "#1a1c1c",
        "tertiary": "#000000",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-fixed": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "primary-container": "#1b1b1b",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "secondary": "#5d5f5f",
        "tertiary-container": "#1b1b1b",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#616363",
        "primary-fixed": "#e2e2e2",
        "secondary-container": "#dfe0e0",
        "tertiary-fixed-dim": "#c6c6c6",
        "secondary-fixed": "#e2e2e2",
        "surface-container": "#eeeeee",
        "on-surface-variant": "#4c4546",
        "inverse-primary": "#c6c6c6",
        "background": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "error-container": "#ffdad6",
        "accent": "#1a3a52",
        "accent-light": "#2d5a7b"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      fontFamily: {
        "headline-md": ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "sans-serif"],
        "headline-xl": ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "sans-serif"],
        "label-mono": ["ui-monospace", "SF Mono", "Menlo", "Monaco", "monospace"],
        "headline-lg": ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "sans-serif"],
        "body-md": ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "sans-serif"],
        "body-lg": ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "sans-serif"],
        "mono": ["ui-monospace", "SF Mono", "Menlo", "Monaco", "monospace"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.15", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-xl": ["72px", { lineHeight: "0.95", letterSpacing: "-0.05em", fontWeight: "700" }],
        "label-mono": ["12px", { lineHeight: "1.2", fontWeight: "500", letterSpacing: "0.5px" }],
        "headline-lg": ["48px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "650" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}